#生产环境


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/blog?useSSL=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 199961





#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
  level:
    root: warn
    com.blog: info
  file:
    path: log/blog-pro.log

server:
  port: 8081
